spring.application.name=Petistaan-OwnerMS
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/petistaan_owner?ssl=false
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
pet.service.base.url=http://localhost:8082/pets
mail.service.base.url=http://localhost:8083/mails
